version: '3.8'

services:
  # 1. VERİTABANI (Stabil Sürüm)
  mongodb:
    image: mongo:4.4
    container_name: astro-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - astro_data:/data/db

  # 2. BACKEND (Node.js & ONNX Model)
  backend:
    build: ./backend
    container_name: astro-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Node.js, Docker iç ağındaki 'mongodb' ismini tanıyacak
      - MONGO_URI=mongodb://mongodb:27017/astro-mongo
      - PORT=8080
    depends_on:
      - mongodb

  # 3. FRONTEND (Arayüz)
  frontend:
    build: ./frontend
    container_name: astro-frontend
    restart: unless-stopped
    ports:
      # Arkadaşın front-end için Dockerfile'da muhtemelen Nginx (port 80) kullandı.
      # Dışarıya 3000 portundan açıyoruz.
      - "3000:80"
    depends_on:
      - backend

volumes:
  astro_data: